name: Java CI with Maven

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # или другой дистрибутив, например 'zulu'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Create ZIP package
        run: zip -j target/app.zip target/*.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-package
          path: target/app.zip

  release:
    needs
