name: Java CI with Maven

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Find JAR file
        run: |
          jar=$(find target -name '*.jar' -type f)
          echo "Found JAR file: $jar"
          echo "::set-output name=jar::$jar"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ github.event.repository.releases_url }}
          asset_path: ${{ steps.find_jar.outputs.jar }}
          asset_name: app.jar
          asset_content_type: application/java-archive
