name: Java CI with Maven

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Package build into ZIP
        run: zip -r my_app.zip target/

      - name: Upload to Release
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
            -H "Content-Type: application/zip" \
            --data-binary "@my_app.zip" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.sha }}/assets?name=my_app.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_TOKEN }}
